name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile binsaver.cpp
      run: clang++ -std=c++17 -o binsaver binsaver.cpp

    - name: Run compiled binary
      run: ./binsaver || echo "Execution failed but continuing..."

    - name: Upload compiled binary
      uses: actions/upload-artifact@v4
      with:
        name: binsaver
        path: ./binsaver


